// <auto-generated />
using System;
using FindTeaBackEnd.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FindTeaBackEnd.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20240810085259_AddedDrinksRating")]
    partial class AddedDrinksRating
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FindTeaBackEnd.Models.Drink", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("Storeid")
                        .HasColumnType("integer");

                    b.Property<string>("drink_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("drink_rating")
                        .HasColumnType("real");

                    b.Property<bool>("is_hot_drink")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_registered")
                        .HasColumnType("boolean");

                    b.Property<int>("store_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("Storeid");

                    b.ToTable("Drinks");
                });

            modelBuilder.Entity("FindTeaBackEnd.Models.Rating", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("Drinkid")
                        .HasColumnType("integer");

                    b.Property<int>("drink_id")
                        .HasColumnType("integer");

                    b.Property<float>("drink_rating")
                        .HasColumnType("real");

                    b.Property<int>("store_id")
                        .HasColumnType("integer");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("Drinkid");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("FindTeaBackEnd.Models.Store", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("address_hint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("rating")
                        .HasColumnType("real");

                    b.Property<string>("store_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("thumbnailURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("FindTeaBackEnd.Models.Drink", b =>
                {
                    b.HasOne("FindTeaBackEnd.Models.Store", null)
                        .WithMany("drinks")
                        .HasForeignKey("Storeid");
                });

            modelBuilder.Entity("FindTeaBackEnd.Models.Rating", b =>
                {
                    b.HasOne("FindTeaBackEnd.Models.Drink", null)
                        .WithMany("ratings")
                        .HasForeignKey("Drinkid");
                });

            modelBuilder.Entity("FindTeaBackEnd.Models.Drink", b =>
                {
                    b.Navigation("ratings");
                });

            modelBuilder.Entity("FindTeaBackEnd.Models.Store", b =>
                {
                    b.Navigation("drinks");
                });
#pragma warning restore 612, 618
        }
    }
}
